name: modsuite

volumes:
  plugins:

services:
  init:
    image: ubuntu
    command: |
      cp -v /data/plugins/ChatMod/config.${INCLUDE_BOT:-exclude}.yml /data/plugins/ChatMod/config.yml
    volumes:
      - /srv/cred/discord:/srv/cred/discord:rw
      - plugins:/data/plugins:rw

  dev_server:
    build:
      context: run/spigot
    restart: on-failure
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      TZ: "Europe/Berlin"
      MEMORYSIZE: "4G"
      DEBUG: 'true'
    volumes:
      # dev plugins from image
      - plugins:/data/plugins:rw
      # avoid world wipes
      - ${DEV_HOME}/run/spigot/world:/data/world:rw
      - ${DEV_HOME}/run/spigot/world_nether:/data/world_nether:rw
      - ${DEV_HOME}/run/spigot/world_the_end:/data/world_the_end:rw
      # discord bot token location
      - /srv/cred/discord:/srv/cred/discord:r
    ports:
      - "0.0.0.0:5005:5005"
      - "0.0.0.0:25565:25565"
    depends_on:
      init:
        condition: service_completed_successfully
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  discordbot:
    build:
      context: ChatMod/discord
    restart: on-failure
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
      DEBUG: 'true'
    volumes:
      - /srv/cred/discord:/srv/cred/discord:r
    ports:
      - "0.0.0.0:5006:5006"
    depends_on:
      init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy

  database:
    hostname: database
    image: mariadb:lts
    restart: unless-stopped
    environment:
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
      MARIADB_DATABASE: dev
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ${DEV_HOME}/run/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql:r
    ports:
      - "0.0.0.0:53306:3306"

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "0.0.0.0:55672:15672"
